name: Build and Push Docker Image

on:
  push:
    branches: ["main"]
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write   # necesario para subir a GHCR

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Installing Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        working-directory: ./backend
        run: |
          python -m pip install -r requirements.txt
          python -m pip install pytest

      - name: Running Pytest
        working-directory: ./backend
        run: |
          python -m pytest test_main.py

      - name: Run pytest and export report
        working-directory: ./backend
        run: |
          pytest --junitxml=pytest-report.xml
          
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: pytest-report
          path: backend/pytest-report.xml
          
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine image tags
        id: vars
        run: |
          REPO_LOWER=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "REPO_NAME=${REPO_LOWER}" >> $GITHUB_ENV

          echo "debugging: ${GITHUB_REF}"

          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            echo "TAG=${GITHUB_REF_NAME}" >> $GITHUB_ENV
          else
            echo "TAG=latest" >> $GITHUB_ENV
          fi

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ env.REPO_NAME }}:${{ env.TAG }} ./backend
      
      - name: Start App with Docker Compose
        run: |
          docker compose -p practicas up -d
      
      - name: Install Locust
        run: |
          python -m pip install locust
      
      - name: Run Locust tests
        run: |
          locust -f locustfile.py \
            --headless \
            --host=http://localhost:8088 \
            --users 500 \
            --spawn-rate 100 \
            --run-time 1m \
            --exit-code-on-error true \
            --fail-request-avg-response-time 1000

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ env.REPO_NAME }}:${{ env.TAG }}
