name: Build and Push Docker Image

on:
  push:
    branches: ["main"]
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write   # necesario para subir a GHCR

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Installing Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        working-directory: ./backend
        run: |
          python -m pip install -r requirements.txt
      
      - name: Running Pytest
        working-directory: ./backend
        run: |
          pytest tests_main.py
          
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine image tags
        id: vars
        run: |
          REPO_LOWER=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "REPO_NAME=${REPO_LOWER}" >> $GITHUB_ENV

          echo "debugging: ${GITHUB_REF}"

          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            echo "TAG=${GITHUB_REF_NAME}" >> $GITHUB_ENV
          else
            echo "TAG=latest" >> $GITHUB_ENV
          fi

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ env.REPO_NAME }}:${{ env.TAG }} ./backend

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ env.REPO_NAME }}:${{ env.TAG }}
